resources:
  pipelines:
    data_engineering_pipeline:
      name: data-engineering-pipeline-test
      serverless: true
      catalog: workspace
      schema: bronze

      libraries:
        - file:
            path: ../src/bronze/bronze_pipeline.py
        - file:
            path: ../src/silver/silver_pipeline.py
