resources:
  pipelines:
    data_engineering_pipeline:
      name: data-engineering-pipeline
      serverless: true
      catalog: main
      schema: bronze

      libraries:
        - file:
            path: ../src/bronze/bronze_pipeline.py
